services:
  backend:
    build:
      context: ./backend
      dockerfile: backend/Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - GROQ_API_KEY=${API_KEY}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=AI_Voice_Assistant

volumes:
  db_data: